apiVersion: v1
kind: Pod
metadata:
  name: mofed-test-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net
spec:
  restartPolicy: OnFailure
  containers:
  - image: mellanox/rping-test
    name: mofed-test-ctr
    securityContext:
      privileged: true
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      requests:
        mellanox.com/mlx5_vf: '1'
      limits:
        mellanox.com/mlx5_vf: '1'
    command:
    - sh
    - -c
    - |
      ls -l /dev/infiniband /sys/class/net
      sleep 1000000
  nodeName: node-0

---

apiVersion: v1
kind: Pod
metadata:
  name: mofed-test-pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net
spec:
  restartPolicy: OnFailure
  containers:
  - image: mellanox/rping-test
    name: mofed-test-ctr
    securityContext:
      privileged: true
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      requests:
        mellanox.com/mlx5_vf: '1'
      limits:
        mellanox.com/mlx5_vf: '1'
    command:
    - sh
    - -c
    - |
      ls -l /dev/infiniband /sys/class/net
      sleep 1000000
  nodeName: node-1
