apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServerExtraArgs:
  enable-admission-plugins: PodSecurityPolicy
clusterName: kubernetes
controllerManager: {}
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kubernetesVersion: v1.20.5
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
NodeRegistrationOptions: