apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-hca-ds
  labels:
    k8s-app: test-hca-ds
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  selector:
    matchLabels:
      name: test-hca-ds
  template:
    metadata:
      labels:
        name: test-hca-ds
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
    spec:
      restartPolicy: Always
      containers:
      - image: mellanox/rping-test
        name: mofed-test-ctr
        securityContext:
          capabilities:
            add: [ "IPC_LOCK" ]
        # resources:
        #   limits:
        #     rdma/MLNX_VF: 1
        command:
        - sh
        - -c
        - |
          ls -l /dev/infiniband /sys/class/net
          sleep 1000000