FROM poanpan/cascade:mxnet
MAINTAINER myles.l.pan@gmail.com

COPY build/ /root/build
COPY config/ /root/config
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
ENV DERECHO_CONF_FILE=/root/derecho.cfg
ARG CASCADE_BRANCH=master
RUN ["chmod", "+x", "/root/build/build-derecho.sh"]
RUN ["chmod", "+x", "/root/build/build-cascade.sh"]
RUN ["chmod", "+x", "/root/config/config-cascade.sh"]
RUN ["bash", "/root/build/build-derecho.sh"]
RUN ["/root/build/build-cascade.sh"]