FROM poanpan/cascade:mxnet
MAINTAINER myles.l.pan@gmail.com

COPY build/ /root/build
RUN ["chmod", "+x", "/root/build/build-derecho.sh"]
RUN ["chmod", "+x", "/root/build/build-cascade.sh"]

RUN ["bash", "/root/build/build-derecho.sh"]
ARG CASCADE_BRANCH=master
RUN ["/root/build/build-cascade.sh"]