# The built docker image: poanpan/cascade:upgrade-cascade-gpu
FROM poanpan/cascade:upgrade-derecho-gpu
MAINTAINER myles.l.pan@gmail.com

ENV DERECHO_CONF_FILE=/root/derecho.cfg
COPY build/ /root/workspace/build

ARG CASCADE_BRANCH=master
ENV CASCADE_BRANCH=$CASCADE_BRANCH

# RUN ["build/build-cascade.sh", "Debug", "USE_VERBS_API"]
RUN ["build/build-cascade.sh", "Debug", "no"]

COPY scripts/ /root/workspace/scripts
RUN ["scripts/prepare-regression-test.sh"]
WORKDIR /root/workspace/