apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: whereabouts-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "whereaboutsexample",
      "type": "macvlan",
      "master": "eno50",
      "mode": "bridge",
      "ipam": {
        "type": "whereabouts",
        "datastore": "kubernetes",
        "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
        "range": "10.199.200.0/24",
        "range_start": "10.199.200.100",
        "log_file" : "/tmp/whereabouts.log",
        "gateway": "10.199.200.1"
      }
    }'