apiVersion: v1
kind: Pod
metadata:
  # namespace: sriov-network-operator
  name: old-mofed-test-pod0
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net
spec:
  restartPolicy: OnFailure
  containers:
  - image: songweijia/devel:cascade-setup-ubuntu20.04
    name: mofed-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      requests:
        openshift.io/mlx5_vf: '1'
      limits:
        openshift.io/mlx5_vf: '1'
    command:
    - sh
    - -c
    - |
      ls -l /dev/infiniband /sys/class/net
      sleep 1000000
  nodeName: node0

---

apiVersion: v1
kind: Pod
metadata:
  # namespace: sriov-network-operator
  name: old-mofed-test-pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net
spec:
  restartPolicy: OnFailure
  containers:
  - image: songweijia/devel:cascade-setup-ubuntu20.04
    name: mofed-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]
    resources:
      requests:
        openshift.io/mlx5_vf: '1'
      limits:
        openshift.io/mlx5_vf: '1'
    command:
    - sh
    - -c
    - |
      ls -l /dev/infiniband /sys/class/net
      sleep 1000000
  nodeName: node1
