apiVersion: v1
kind: Pod
metadata:
  namespace: sriov-network-operator
  name: new-mofed-test-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net
spec:
  restartPolicy: OnFailure
  containers:
  - image: poanpan/ubuntu-net-rdma
    name: mofed-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]     
    resources:
      requests:
        openshift.io/mlx5_vf: '1'
      limits:
        openshift.io/mlx5_vf: '1'
    command:
    - sh
    - -c
    - sleep inf
  nodeName: node-0
---
apiVersion: v1
kind: Pod
metadata:
  namespace: sriov-network-operator
  name: new-mofed-test-pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net
spec:
  restartPolicy: OnFailure
  containers:
  - image: poanpan/ubuntu-net-rdma
    name: mofed-test-ctr
    securityContext:
      capabilities:
        add: [ "IPC_LOCK" ]     
    resources:
      requests:
        openshift.io/mlx5_vf: '1'
      limits:
        openshift.io/mlx5_vf: '1'
    command:
    - sh
    - -c
    - sleep inf
  nodeName: node-1